name: Build AAR

on:
  push:
    branches: [ master ]  # 或其他你常用的分支

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 8

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build AAR
        run: ./gradlew :xpmodulemultidex:assembleRelease --console=plain

      - name: Upload AAR Artifact
        uses: actions/upload-artifact@v2
        with:
          name: xpmodulemultidex-release-aar
          path: xpmodulemultidex/build/outputs/aar/*.aar

